name = "RankingModels"
uuid = "681c28ee-283f-446c-87c4-82a4477d63d7"
authors = ["Adam L. Pintar <adampintar@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
